import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

function resolveVaultPluginDir() {
  if (process.env.VAULT_PLUGIN_DIR) return process.env.VAULT_PLUGIN_DIR.trim();
  try {
    const fromFile = fs.readFileSync(".vault-path", "utf8").trim();
    if (fromFile) return fromFile;
  } catch {
    // No .vault-path file — fall through and skip the vault copy.
  }
  return null;
}

const VAULT_PLUGIN_DIR = resolveVaultPluginDir();

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await ctx.rebuild();
  ctx.dispose();

  // Copy to vault (only if VAULT_PLUGIN_DIR env var is set)
  if (VAULT_PLUGIN_DIR) {
    fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
    fs.copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
    fs.copyFileSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
    if (fs.existsSync("styles.css")) {
      fs.copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
    }
    console.log(`\n✓ Plugin installed to vault at:\n  ${VAULT_PLUGIN_DIR}\n`);
  } else {
    console.log("\n⚠ VAULT_PLUGIN_DIR not set — skipping vault copy.");
    console.log("  Copy main.js, manifest.json, and styles.css manually to your vault's plugin folder,");
    console.log("  or re-run with: VAULT_PLUGIN_DIR=/path/to/.obsidian/plugins/research-importer npm run build\n");
  }
} else {
  await ctx.watch();
}
