/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var p=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var f=Object.prototype.hasOwnProperty;var b=(a,t)=>{for(var i in t)p(a,i,{get:t[i],enumerable:!0})},w=(a,t,i,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of d(t))!f.call(a,n)&&n!==i&&p(a,n,{get:()=>t[n],enumerable:!(e=u(t,n))||e.enumerable});return a};var m=a=>w(p({},"__esModule",{value:!0}),a);var $={};b($,{default:()=>l});module.exports=m($);var o=require("obsidian"),l=class extends o.Plugin{async onload(){this.addCommand({id:"fetch-doi-metadata",name:"Fetch DOI Metadata",checkCallback:t=>(t||this.fetchAndCreateNote(),!0)})}async fetchAndCreateNote(){var i;let t=await this.promptForDOI();if(t)try{let e=await this.fetchDOIMetadata(t),n=await this.fetchDOIMetadataAsBibTeX(t,e),r=e.title.replace(/[\/\\:*?"<>|]/g,""),s=((i=e.author[0])==null?void 0:i.family)||"Unknown Author",c=this.getYear(e),y=`${r} - (${c}) - ${s}`,g=this.generateNoteContent(e,n);this.createNewNote(y,g,e)}catch(e){new o.Notice("Failed to fetch DOI metadata: "+e.message)}}async promptForDOI(){return new Promise(t=>{new h(this.app,"Enter DOI",e=>{t(e||null)}).open()})}async fetchDOIMetadata(t){let i=`https://doi.org/${encodeURIComponent(t)}`,e=await fetch(i,{headers:{Accept:"application/vnd.citationstyles.csl+json"}});if(!e.ok)throw new Error(`Error: ${e.statusText}`);return await e.json()}async fetchDOIMetadataAsBibTeX(t,i){let e=`https://doi.org/${encodeURIComponent(t)}`,n=await fetch(e,{headers:{Accept:"application/x-bibtex"}});if(!n.ok)throw new Error(`Error: ${n.statusText}`);let r=await n.text();r=r.replace(/^\s+/,""),r=r.replace(/[\r\n]+/g," ").replace(/\s+/g," "),r=r.replace(/\s*,\s*(?=\w+\s*=)/g,`,
  `);let s=this.getCiteKey(i);if(await this.isCiteKeyDuplicate(s))throw new Error(`Cite key "${s}" is already in use.`);return r=r.replace(/(@[^{]+{)[^,]+,/,`$1${s},`),r}sanitizeString(t){return t.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9-_]/g,"_").replace(/_+/g,"_").replace(/_$/,"")}async isCiteKeyDuplicate(t){var e;let i=this.app.vault.getMarkdownFiles();for(let n of i){let r=await this.app.vault.read(n),s=(e=this.app.metadataCache.getFileCache(n))==null?void 0:e.frontmatter;if(s&&s.cite_key===t)return!0}return!1}getCiteKey(t){var r;let i=this.sanitizeString((r=t.author[0])==null?void 0:r.family.replace(/\s+/g,""))||"UnknownAuthor",e=this.getYear(t),n=this.sanitizeString(t.title.split(" ")[0])||"UnknownTitle";return`${i}${e}${n}`}getYear(t){return t.issued["date-parts"][0][0]||"UnknownYear"}getType(t){return{"journal-article":"article",book:"book","book-chapter":"inbook"}[t.type]||"article"}generateNoteContent(t,i){return`---
type: ${this.getType(t)}
cite_key: ${this.getCiteKey(t)}
title: "${t.title}"
authors:
${t.author.map(e=>`  - ${e.family} ${e.given}`).join(`
`)}
year: ${this.getYear(t)}
publisher: "${t.publisher}"
journal: "${t["container-title"]}"
doi: ${t.DOI}
url: ${t.URL}
bibtex: |-
  ${i}
has_attachments: false
tags:
  - bibliography
---

## Attachments

- PDF: 
- Supplemental: 

## Comments
`}async createNewNote(t,i,e){let s=`${this.getType(e)==="article"?"Research/Bibliography/Articles":"Research/Bibliography/Books"}/${t}.md`;await this.app.vault.create(s,i);let c=this.app.vault.getAbstractFileByPath(s);c instanceof o.TFile?await this.app.workspace.getLeaf(!0).openFile(c):new o.Notice("Failed to open the newly created note.")}},h=class extends o.Modal{constructor(i,e,n){super(i);this.placeholder=e,this.callback=n}onOpen(){let{contentEl:i}=this;i.createEl("h3",{text:this.placeholder});let e=i.createEl("div",{cls:"doi-container"});e.style.display="flex",e.style.flexDirection="column",e.style.alignItems="center",e.style.justifyContent="center",e.style.width="100%",e.style.padding="20px",e.style.boxSizing="border-box";let n=e.createEl("input",{type:"text"});n.style.width="100%",n.style.marginBottom="10px",n.style.padding="10px",n.style.border="1px solid #ccc",n.style.borderRadius="4px",n.focus();let r=e.createEl("button",{text:"Submit"});r.style.border="none",r.style.padding="10px 20px",r.style.borderRadius="4px",r.style.cursor="pointer",r.onclick=()=>{this.callback(n.value.trim()),this.close()},n.addEventListener("keydown",s=>{s.key==="Enter"&&(this.callback(n.value.trim()),this.close())})}onClose(){let{contentEl:i}=this;i.empty()}};
