/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var p=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var u=Object.getOwnPropertyNames;var b=Object.prototype.hasOwnProperty;var f=(s,t)=>{for(var n in t)p(s,n,{get:t[n],enumerable:!0})},w=(s,t,n,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of u(t))!b.call(s,i)&&i!==n&&p(s,i,{get:()=>t[i],enumerable:!(e=d(t,i))||e.enumerable});return s};var m=s=>w(p({},"__esModule",{value:!0}),s);var $={};f($,{default:()=>l});module.exports=m($);var o=require("obsidian"),l=class extends o.Plugin{async onload(){this.addCommand({id:"fetch-doi-metadata",name:"Fetch DOI Metadata",checkCallback:t=>(t||this.fetchAndCreateNote(),!0)})}async fetchAndCreateNote(){var n;let t=await this.promptForDOI();if(t)try{let e=await this.fetchDOIMetadata(t),i=await this.fetchDOIMetadataAsBibTeX(t,e),r=e.title.replace(/[\/\\:*?"<>|]/g,""),a=((n=e.author[0])==null?void 0:n.family)||"Unknown Author",c=this.getYear(e),y=`${r} - (${c}) - ${a}`,g=this.generateNoteContent(e,i);this.createNewNote(y,g,e)}catch(e){new o.Notice("Failed to fetch DOI metadata: "+e.message)}}async promptForDOI(){return new Promise(t=>{new h(this.app,"Enter DOI",e=>{t(e||null)}).open()})}async fetchDOIMetadata(t){let n=`https://doi.org/${encodeURIComponent(t)}`,e=await fetch(n,{headers:{Accept:"application/vnd.citationstyles.csl+json"}});if(!e.ok)throw new Error(`Error: ${e.statusText}`);return await e.json()}async fetchDOIMetadataAsBibTeX(t,n){let e=`https://doi.org/${encodeURIComponent(t)}`,i=await fetch(e,{headers:{Accept:"application/x-bibtex"}});if(!i.ok)throw new Error(`Error: ${i.statusText}`);let r=await i.text();r=r.replace(/^\s+/,""),r=r.replace(/[\r\n]+/g," ").replace(/\s+/g," "),r=r.replace(/\s*,\s*(?=\w+\s*=)/g,`,
  `);let a=this.getCiteKey(n);return r=r.replace(/(@[^{]+{)[^,]+,/,`$1${a},`),r}sanitizeString(t){return t.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9-_]/g,"_").replace(/_+/g,"_").replace(/_$/,"")}getCiteKey(t){var r;let n=this.sanitizeString((r=t.author[0])==null?void 0:r.family.replace(/\s+/g,""))||"UnknownAuthor",e=this.getYear(t),i=this.sanitizeString(t.title.split(" ")[0])||"UnknownTitle";return`${n}${e}${i}`}getYear(t){return t.issued["date-parts"][0][0]||"UnknownYear"}getType(t){return{"journal-article":"article",book:"book","book-chapter":"inbook"}[t.type]||"article"}generateNoteContent(t,n){return`---
type: ${this.getType(t)}
cite_key: ${this.getCiteKey(t)}
title: "${t.title}"
authors:
${t.author.map(e=>`  - ${e.family} ${e.given}`).join(`
`)}
year: ${this.getYear(t)}
publisher: "${t.publisher}"
journal: "${t["container-title"]}"
doi: ${t.DOI}
url: ${t.URL}
bibtex: |-
  ${n}
has_attachments: false
tags:
  - bibliography
---

## Attachments

- PDF: 
- Supplemental: 

## Comments
`}async createNewNote(t,n,e){let a=`${this.getType(e)==="article"?"Research/Bibliography/Articles":"Research/Bibliography/Books"}/${t}.md`;await this.app.vault.create(a,n);let c=this.app.vault.getAbstractFileByPath(a);c instanceof o.TFile?await this.app.workspace.getLeaf(!0).openFile(c):new o.Notice("Failed to open the newly created note.")}},h=class extends o.Modal{constructor(n,e,i){super(n);this.placeholder=e,this.callback=i}onOpen(){let{contentEl:n}=this;n.createEl("h3",{text:this.placeholder});let e=n.createEl("div",{cls:"doi-container"});e.style.display="flex",e.style.flexDirection="column",e.style.alignItems="center",e.style.justifyContent="center",e.style.width="100%",e.style.padding="20px",e.style.boxSizing="border-box";let i=e.createEl("input",{type:"text"});i.style.width="100%",i.style.marginBottom="10px",i.style.padding="10px",i.style.border="1px solid #ccc",i.style.borderRadius="4px",i.focus();let r=e.createEl("button",{text:"Submit"});r.style.border="none",r.style.padding="10px 20px",r.style.borderRadius="4px",r.style.cursor="pointer",r.onclick=()=>{this.callback(i.value.trim()),this.close()},i.addEventListener("keydown",a=>{a.key==="Enter"&&(this.callback(i.value.trim()),this.close())})}onClose(){let{contentEl:n}=this;n.empty()}};
